apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: meshapp 
  annotations:
    avp.kubernetes.io/path: "secret/data/dbcreds"
type: Opaque
data:
  username: <DB_USER>
  password: <DB_PASSWORD>
